export { ExploreLazyPage } from './ExplorePage/ui/ExploreLazyPage'
export { LoginLazyPage } from './LoginPage/ui/LoginLazyPage'
export { RegisterLazyPage } from './RegisterPage/ui/RegisterLazyPage'
export { ProfileLazyPage } from './ProfilePage/ui/ProfileLazyPage'
export { UserLazyPage } from './UserPage/ui/UserLazyPage'
export { MessengerLazyPage } from './MessengerPage/ui/MessengerLazyPage'